schema_version: 1

context:
  name: ms_deisotope
  version: 0.0.56

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/ms_deisotope-${{ version }}.tar.gz
  sha256: 8121f35e4cdd3d558822b525fda2f23d30545f96391cd09f3abbb0131e78f218

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - ms-index = ms_deisotope.tools.indexing:main
      - ms-view = ms_deisotope.tools.view:main
      - ms-deisotope = ms_deisotope.tools.deisotoper.main:deisotope

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy

    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - setuptools
    - pip
    - wheel
    - cython
    # libraries
    - numpy >=2.0.0
    - brain-isotopic-distribution >=1.5.8
    - ms_peak_picker >=0.1.46
  run:
    - python
    - numpy >=2.0.0
    - scipy
    - six
    - dill
    - ms_peak_picker >=0.1.46
    - brain-isotopic-distribution >=1.5.8
    - pyteomics >=4.6.2
    - lxml
    - psims >=1.3.0
    - python-idzip >=0.3.2
    - pyzstd
    - click
    - matplotlib-base

tests:
  - python:
      imports:
        - ms_deisotope
      pip_check: true
  - requirements:
      run:
        - pytest
        - xorg-libx11 # for ms-view --help
    files:
      source:
        - tests/
    script:
      - ms-index --help
      - ms-view --help
      - ms-deisotope --help
      - pytest -vvv tests/test_library.py

about:
  summary: Access, Deisotope, and Charge Deconvolute Mass Spectra
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/mobiusklein/ms_deisotope

extra:
  recipe-maintainers:
    - hadim
